version: "3.7"
services:
  superset:
    image: apache/superset:1.0.1
    container_name: superset_app
    command: ["bash", "/app/superset_home/entrypoint.sh"]
    tty: true
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    environment:
      - SUPERSET_CONFIG_PATH=/app/superset_home/test_config.py
    volumes:
      - ./scripts/entrypoint.sh:/app/superset_home/entrypoint.sh
      - ./tests/superset_test_config.py:/app/superset_home/test_config.py